version: '3.8'

services:
  api1: &app
    hostname: api1
    image: rinha-api:latest
    build:
      context: .
    container_name: api1
    ports:
      - 8080:8080
    environment:
      - SERVER_PORT=8080
      - DATABASE_URL=jdbc:postgresql://db:5432/rinha-db
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
    depends_on:
      - db
    networks:
      - app-network

  api2:
    <<: *app
    container_name: api2
    hostname: api2
    ports:
      - 8081:8081
    environment:
      - SERVER_PORT=8081

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '0.50GB'
    networks:
      - app-network

  db:
    image: postgres
    container_name: postgres-rinha
    ports:
      - "5454:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rinha-db

    networks:
      - app-network


networks:
  app-network:
